import { ArrowLeft, Clock3, Film, HardDrive, Images, QrCode } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import { results } from '../data'
import { Button, ImageWithFallback, PageHeader, StatusBadge } from '../components'

export function DriveDetailsScreen({ onBack }: { onBack: () => void }) {
  const { t } = useTranslation()
  const stats = [{ icon: Film, key: 'drive.videos', value: '642' }, { icon: Images, key: 'dashboard.keyframes', value: '18,432' }, { icon: Clock3, key: 'drive.duration', value: '86:42:18' }, { icon: HardDrive, key: 'drive.size', value: '4.72 TB' }]
  return <div className="flex h-full min-w-0 flex-col"><PageHeader title={t('drive.title')} subtitle="/Volumes/ARCHIVE_NORTH · FF-A7C2-91D4" action={<div className="flex items-center gap-2"><StatusBadge status="connected" /><Button><QrCode size={14} />{t('dashboard.qr')}</Button></div>} /><div className="min-h-0 flex-1 overflow-auto p-4"><Button variant="ghost" onClick={onBack} className="mb-3 px-1"><ArrowLeft size={14} className="rtl-flip" />{t('drive.back')}</Button><section className="grid grid-cols-[repeat(auto-fit,minmax(160px,1fr))] gap-2">{stats.map(({ icon: Icon, key, value }) => <div key={key} className="ff-card flex items-center gap-3 p-3"><Icon size={17} className="text-daylight" /><div><p className="ff-mono text-[14px] font-medium">{value}</p><p className="mt-0.5 text-[9px] text-muted">{t(key)}</p></div></div>)}</section><h2 className="mt-5 ff-section-title">{t('drive.library')}</h2><section className="mt-2 grid grid-cols-[repeat(auto-fill,minmax(200px,1fr))] gap-3">{results.slice(0, 4).map(item => <article key={item.id} className="ff-card overflow-hidden"><ImageWithFallback src={item.image} alt={item.video} className="aspect-video w-full" /><div className="p-2.5"><p className="ff-mono truncate text-[10px]">{item.video}</p><p className="ff-mono mt-1 text-[9px] text-muted">{item.timestamp}</p></div></article>)}</section><h2 className="mt-5 ff-section-title">{t('drive.gallery')}</h2><section className="mt-2 grid grid-cols-[repeat(auto-fill,minmax(130px,1fr))] gap-1">{[...results, ...results].map((item, index) => <ImageWithFallback key={`${item.id}-${index}`} src={item.image} alt={`${item.video} ${index + 1}`} className="aspect-video w-full rounded-[3px]" />)}</section></div></div>
}
