import { ChevronDown, Search } from 'lucide-react'
import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import { results } from '../data'
import { Button, ImageWithFallback, Modal, PageHeader, SearchInput } from '../components'

export function ScenesScreen() {
  const { t } = useTranslation()
  const [selected, setSelected] = useState<(typeof results)[number] | null>(null)
  return <div className="flex h-full min-w-0 flex-col"><PageHeader title={t('scenes.title')} subtitle={t('scenes.subtitle')} /><div className="flex min-h-0 flex-1 flex-col overflow-auto"><div className="grid grid-cols-[minmax(240px,1fr)_auto] items-center gap-2 border-b border-line bg-surface p-3 max-[1180px]:grid-cols-1"><SearchInput placeholder={t('scenes.search')} className="w-full" /><div className="flex min-w-0 flex-wrap items-center gap-1"><span className="ff-badge me-1 shrink-0 border-line bg-window text-muted">{t('common.planned')}</span>{['lighting', 'time', 'shooting'].map(filter => <Button key={filter} variant="ghost" className="h-8 min-h-8 shrink-0">{t(`scenes.${filter}`)}<ChevronDown size={12} /></Button>)}</div></div><section className="grid grid-cols-[repeat(auto-fill,minmax(min(100%,210px),1fr))] gap-3 p-4">{results.map(result => <button key={result.id} onClick={() => setSelected(result)} className="ff-focus group ff-card overflow-hidden text-start hover:border-secondary/40"><div className="relative aspect-video overflow-hidden"><ImageWithFallback src={result.image} alt={result.video} className="size-full transition duration-200 group-hover:scale-[1.015]" /><span className="ff-mono absolute bottom-1.5 end-1.5 bg-black/70 px-1.5 py-0.5 text-[9px] text-white">{result.timestamp}</span></div><div className="p-2.5"><p className="ff-mono truncate text-[10px] font-medium">{result.video}</p><div className="mt-2 flex gap-1">{result.tags.map(tag => <span key={tag} className="rounded-[3px] bg-elevated px-1.5 py-0.5 text-[9px] text-muted">{tag}</span>)}</div></div></button>)}</section></div>{selected && <Modal title={t('scenes.detail')} onClose={() => setSelected(null)}><ImageWithFallback src={selected.image} alt={selected.video} className="aspect-video w-full rounded-ff-xs" /><h3 className="ff-mono mt-3 truncate text-[11px] font-medium">{selected.video}</h3><p className="mt-1 flex items-center gap-2 text-[10px] text-muted"><Search size={12} />{selected.drive} · <span className="ff-mono">{selected.timestamp}</span></p></Modal>}</div>
}
